global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'todo-prometheus:9090' ]
  - job_name: 'reactive-todo-service'
    metrics_path: '/reactive-todo-service/actuator/prometheus'
    static_configs:
      - targets: [ 'reactive-todo-service:8080' ]