# This workflow builds and test reactive-todo-service project.
# It is triggered when there is a push to a repository branch, this includes when a commit is pushed, a commit tag is pushed, a branch is deleted, a tag is deleted, or when there is activity on a pull request.

name: Build and test the project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and test the service
        run: mvn verify

      - name: Test Liquibase
        run: |
          docker-compose up -d todo-postgres-db
          mvn liquibase:updateTestingRollback
          docker-compose down -v